dist:
  name: otelcol-custom
  description: Building custom collector instance.
  output_path: ./otel-build-test
exporters:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.100.0
processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.100.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.100.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.100.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.100.0
